version: "3.7"

services:
  coingecko-exporter:
    build: .
    container_name: coingecko-exporter
    environment:
      - CRYPTO_COINS=bitcoin,ethereum,ripple,dogecoin,cardano,safemoon,litecoin,polkadot,chainlink,vechain,tron,zilliqa,digibyte,siacoin
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - public

networks:
  public:
    name: public
